apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-cicd
  labels:
    app: nginx
spec:
  replicas: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: node-todo-cicd
        image: gowtham/node-todo-cicd:v1
        ports:
        - containerPort: 8000
